#!/usr/bin/env node

var program = require('commander');
var client = require('./client');

var endpoint = "http://localhost:3000/api/v1/users"

program
  .option('-p, --page <page #>', 'The page of the response')
  .option('-n, --perpage <# records>', 'The number of records per page')
  .action(function(username) {

    if (!program.page) {
      page = 0
    } else {
      page = program.page - 1
    }

    if (!program.perpage) {
      per_page = 20
    } else {
      per_page = program.perpage
    }

    args = {
      path: { "username": username }, // path substitution var
      parameters: { page: page, per_page: per_page }, // query parameter substitution vars
    };

    // if a resource username is passed, fetch the single resource
    // if (typeof(username) != "undefined") {
    //   endpoint += "/${username}";
    //   args.path.username = username
    //   delete args.parameters
    // }

    console.log(args)
    console.log(endpoint)
    client.get(endpoint, args, function (data, response) {
      console.log(data);
    });
  });

program.parse(process.argv)
